#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/opt/homebrew/share/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/mihir/Downloads/4150/ReadRight 2.0/readright-2.0/readright_app"
export "FLUTTER_FRAMEWORK_SWIFT_PACKAGE_PATH=/Users/mihir/Downloads/4150/ReadRight 2.0/readright-2.0/readright_app/ios/Flutter/ephemeral/Packages/.packages/FlutterFramework"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/mihir/Downloads/4150/ReadRight 2.0/readright-2.0/readright_app/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuNDQuMw==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049ZTFmZDk2M2M2Zg==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049YTRjZTI1N2M2OA==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMi4y"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/mihir/Downloads/4150/ReadRight 2.0/readright-2.0/readright_app/.dart_tool/package_config.json"
